# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T18:54:03+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class AutomotivePartsCompatibilityPolicy(BaseModel):
    categoryId: Optional[str] = Field(
        None,
        description='The category ID to which the automotive-parts-compatibility policies apply.',
    )
    categoryTreeId: Optional[str] = Field(
        None,
        description='A value that indicates the root node of the category tree used for the response set. Each marketplace is based on a category tree whose root node is indicated by this unique category ID value. All category policy information returned by this call pertains to the categories included below this root node of the tree.    <br><br>A <i>category tree</i> is a hierarchical framework of eBay categories that begins at the root node of the tree and extends to include all the child nodes in the tree. Each child node in the tree is an eBay category that is represented by a unique <b>categoryId</b> value. Within a category tree, the root node has no parent node and <i>leaf nodes</i> are nodes that have no child nodes.',
    )
    compatibilityBasedOn: Optional[str] = Field(
        None,
        description="Indicates whether the category supports parts compatibility by either <code>ASSEMBLY</code> or by <code>SPECIFICATION</code>. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/metadata/types/sel:CompatibilityTypeEnum'>eBay API documentation</a>",
    )
    compatibleVehicleTypes: Optional[List[str]] = Field(
        None,
        description='Indicates the compatibility classification of the part based on high-level vehicle types.',
    )
    maxNumberOfCompatibleVehicles: Optional[int] = Field(
        None,
        description='Specifies the maximum number of compatible vehicle-applications allowed per item.',
    )


class ErrorParameter(BaseModel):
    name: Optional[str] = Field(
        None, description='Name of the entity that threw the error.'
    )
    value: Optional[str] = Field(None, description='A description of the error.')


class ExtendedProducerResponsibility(BaseModel):
    enabledForVariations: Optional[bool] = Field(
        None,
        description='An indication of whether the attribute can be enabled for listing variations.<br /><br />If the value is <code>true</code>, the attribute may be specified at the variation level.',
    )
    name: Optional[str] = Field(
        None,
        description="The name of the attribute included in the policy. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/metadata/types/sel:ExtendedProducerResponsibilityEnum'>eBay API documentation</a>",
    )
    usage: Optional[str] = Field(
        None,
        description="The usage guidelines for the attribute, in the specified marketplace. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/metadata/types/sel:GenericUsageEnum'>eBay API documentation</a>",
    )


class ExtendedProducerResponsibilityPolicy(BaseModel):
    categoryId: Optional[str] = Field(
        None,
        description='The unique identifier for the category under which the policy applies.',
    )
    categoryTreeId: Optional[str] = Field(
        None,
        description='The unique identifier for the category tree under which the policy applies.',
    )
    supportedAttributes: Optional[List[ExtendedProducerResponsibility]] = Field(
        None,
        description='The details regarding the attributes included in the policy, such as their usage guidelines and whether they can be specified at the listing variation level.',
    )


class HazardStatement(BaseModel):
    statementDescription: Optional[str] = Field(
        None,
        description="The description of the statement localized to the default language of the marketplace. For sample values, see <a href='/api-docs/sell/static/metadata/feature-regulatorhazmatcontainer.html#Hazard'>Hazard statement sample values</a>.",
    )
    statementId: Optional[str] = Field(
        None,
        description="The identifier of the statement. For sample values, see <a href='/api-docs/sell/static/metadata/feature-regulatorhazmatcontainer.html#Hazard'>Hazard statement sample values</a>.",
    )


class ItemCondition(BaseModel):
    conditionDescription: Optional[str] = Field(
        None,
        description='The human-readable label for the condition (e.g., "New"). This value is typically localized for each site.  <br><br>Note that the display name can vary by category. For example, the description for condition ID <code>1000</code> could be called "New: with Tags" in one category and "Brand New" in another. For details on condition IDs and descriptions, see <a href=\'/api-docs/sell/static/metadata/condition-id-values.html\'>Item condition ID and name values</a>.',
    )
    conditionId: Optional[str] = Field(
        None,
        description="The ID value of the selected item condition. For information on the supported condition ID values, see <a href='/api-docs/sell/static/metadata/condition-id-values.html'>Item condition ID and name values</a>.",
    )
    usage: Optional[str] = Field(
        None,
        description='The value returned in this field indicates if there are any usage restrictions or requirements for the corresponding item condition in the corresponding category.<br /><br /><span class="tablenote"><b>Note:</b> Currently, the only supported value is \'RESTRICTED\', and this field will only be returned for the following conditions: 2000, 2010, 2020, 2030. Sellers must be pre-approved to use any of these item conditions.</span> For implementation help, refer to <a href=\'https://developer.ebay.com/api-docs/sell/metadata/types/sel:UsageEnum\'>eBay API documentation</a>',
    )


class ItemConditionPolicy(BaseModel):
    categoryId: Optional[str] = Field(
        None, description='The category ID to which the item-condition policy applies.'
    )
    categoryTreeId: Optional[str] = Field(
        None,
        description='A value that indicates the root node of the category tree used for the response set. Each marketplace is based on a category tree whose root node is indicated by this unique category ID value. All category policy information returned by this call pertains to the categories included below this root node of the tree.    <br><br>A <i>category tree</i> is a hierarchical framework of eBay categories that begins at the root node of the tree and extends to include all the child nodes in the tree. Each child node in the tree is an eBay category that is represented by a unique <b>categoryId</b> value. Within a category tree, the root node has no parent node and <i>leaf nodes</i> are nodes that have no child nodes.',
    )
    itemConditionRequired: Optional[bool] = Field(
        None,
        description='This flag denotes whether or not you must list the item condition in a listing for the specified category. If set to <code>true</code>, you must specify an item condition for the associated category.',
    )
    itemConditions: Optional[List[ItemCondition]] = Field(
        None,
        description='The item-condition values allowed in the category.<br /><br /><span class="tablenote"><b>Note:</b> The ‘Seller Refurbished’ item condition (condition ID 2500) has been replaced by the \'Excellent - Refurbished\', \'Very Good - Refurbished\', and \'Good - Refurbished\' item conditions in a select number of eBay marketplaces and categories. See the <a href="/api-docs/sell/static/metadata/condition-id-values.html#Category " target="_blank "> eBay Refurbished Program - Category and marketplace support</a> topic for more details.<br/><br/>Similar to the ‘Certified Refurbished’ item condition (condition ID 2000), a seller’s OAuth user token will have to be used instead of an OAuth application token, since each seller must  go through an application and qualification process before using any of these new refurbished item conditions in supported categories. If a seller is not qualified to use the new refurbished item conditions, these item condition values will not be returned by <b>getItemConditionPolicies</b>.</span>',
    )


class ListingStructurePolicy(BaseModel):
    categoryId: Optional[str] = Field(
        None,
        description='The category ID to which the listing-structure policy applies.',
    )
    categoryTreeId: Optional[str] = Field(
        None,
        description='A value that indicates the root node of the category tree used for the response set. Each marketplace is based on a category tree whose root node is indicated by this unique category ID value. All category policy information returned by this call pertains to the categories included below this root node of the tree.    <br><br>A <i>category tree</i> is a hierarchical framework of eBay categories that begins at the root node of the tree and extends to include all the child nodes in the tree. Each child node in the tree is an eBay category that is represented by a unique <b>categoryId</b> value. Within a category tree, the root node has no parent node and <i>leaf nodes</i> are nodes that have no child nodes.',
    )
    variationsSupported: Optional[bool] = Field(
        None,
        description='This flag denotes whether or not the associated category supports listings with item variations. If set to <code>true</code>, the category does support item variations.',
    )


class NegotiatedPricePolicy(BaseModel):
    bestOfferAutoAcceptEnabled: Optional[bool] = Field(
        None,
        description='This flag denotes whether or not the category supports the setting of a price at which best offers are automatically accepted. If set to <code>true</code>, the category does support the setting of an automatic price for best-offers.',
    )
    bestOfferAutoDeclineEnabled: Optional[bool] = Field(
        None,
        description='This flag denotes whether or not the category supports the setting of an auto-decline price for best offers. If set to <code>true</code>, the category does support the setting of an automatic-decline price for best-offers.',
    )
    bestOfferCounterEnabled: Optional[bool] = Field(
        None,
        description='This flag denotes whether or not the category supports the setting for an automatic counter-offer on best offers. If set to <code>true</code>, the category does support the setting of an automatic counter-offer price for best-offers.',
    )
    categoryId: Optional[str] = Field(
        None,
        description='The category ID to which the negotiated-price policies apply.',
    )
    categoryTreeId: Optional[str] = Field(
        None,
        description='A value that indicates the root node of the category tree used for the response set. Each marketplace is based on a category tree whose root node is indicated by this unique category ID value. All category policy information returned by this call pertains to the categories included below this root node of the tree.    <br><br>A <i>category tree</i> is a hierarchical framework of eBay categories that begins at the root node of the tree and extends to include all the child nodes in the tree. Each child node in the tree is an eBay category that is represented by a unique <b>categoryId</b> value. Within a category tree, the root node has no parent node and <i>leaf nodes</i> are nodes that have no child nodes.',
    )


class Pictogram(BaseModel):
    pictogramDescription: Optional[str] = Field(
        None,
        description="The description of the pictogram localized to the default language of the marketplace. For sample values, see <a href='/api-docs/sell/static/metadata/feature-regulatorhazmatcontainer.html#Pictogra'>Pictogram sample values</a>.",
    )
    pictogramId: Optional[str] = Field(
        None,
        description="The identifier of the pictogram. For sample values, see <a href='/api-docs/sell/static/metadata/feature-regulatorhazmatcontainer.html#Pictogra'>Pictogram sample values</a>.",
    )
    pictogramUrl: Optional[str] = Field(None, description='The URL of the pictogram.')


class SalesTaxJurisdiction(BaseModel):
    salesTaxJurisdictionId: Optional[str] = Field(
        None, description='The unique ID for a sales tax jurisdiction.'
    )


class SalesTaxJurisdictions(BaseModel):
    salesTaxJurisdictions: Optional[List[SalesTaxJurisdiction]] = Field(
        None, description='A list of sales tax jurisdictions.'
    )


class SignalWord(BaseModel):
    signalWordDescription: Optional[str] = Field(
        None,
        description="The description of the signal word localized to the default language of the marketplace. For more information, see <a href='/api-docs/sell/static/metadata/feature-regulatorhazmatcontainer.html#Signal'>Signal word information</a>.",
    )
    signalWordId: Optional[str] = Field(
        None,
        description="The identifier of the signal word. For more information, see <a href='/api-docs/sell/static/metadata/feature-regulatorhazmatcontainer.html#Signal'>Signal word information</a>.",
    )


class TimeDuration(BaseModel):
    unit: Optional[str] = Field(
        None,
        description="A time-measurement unit that specifies a singular period of time.  <br><br>A span of time is defined when you apply the value specified in the <b>value</b> field to the value specified for <b>unit</b>.  <br><br>Time-measurement units can be YEAR, MONTH, DAY, and so on. See <b>TimeDurationUnitEnum</b> for a complete list of possible time-measurement units. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/metadata/types/ba:TimeDurationUnitEnum'>eBay API documentation</a>",
    )
    value: Optional[int] = Field(
        None,
        description='An integer that represents an amount of time, as measured by the time-measurement unit specified in the <b>unit</b> field.',
    )


class Error(BaseModel):
    category: Optional[str] = Field(
        None,
        description='The category type for this error or warning. It takes an ErrorCategory object which can have one of three values:<ul><li><code>Application</code>: Indicates an exception or error occurred in the application code or at runtime. Examples include catching an exception in a service\'s business logic, system failures, or request errors from a dependency.</li><li><code>Business</code>: Used when your service or a dependent service refused to continue processing on the resource because of a business rule violation such as "Seller does not ship item to Antarctica" or "Buyer ineligible to purchase an alcoholic item". Business errors are not syntactical input errors.</li><li><code>Request</code>: Used when there is anything wrong with the request, such as authentication, syntactical errors, rate limiting or missing headers, bad HTTP header values, and so on.</li></ul>',
    )
    domain: Optional[str] = Field(
        None, description='Name of the domain containing the service or application.'
    )
    errorId: Optional[int] = Field(
        None,
        description='A positive integer that uniquely identifies the specific error condition that occurred. Your application can use error codes as identifiers in your customized error-handling algorithms.',
    )
    inputRefIds: Optional[List[str]] = Field(
        None,
        description="Identifies specific request elements associated with the error, if any. inputRefId's response is format specific. For JSON, use <i>JSONPath</i> notation.",
    )
    longMessage: Optional[str] = Field(
        None,
        description='An expanded version of message that should be around 100-200 characters long, but is not required to be such.',
    )
    message: Optional[str] = Field(
        None,
        description="An end user and app developer friendly device agnostic message. It explains what the error or warning is, and how to fix it (in a general sense). Its value is at most 50 characters long. If applicable, the value is localized in the end user's requested locale.",
    )
    outputRefIds: Optional[List[str]] = Field(
        None,
        description='Identifies specific response elements associated with the error, if any. Path format is the same as <code>inputRefId</code>.',
    )
    parameters: Optional[List[ErrorParameter]] = Field(
        None,
        description='This optional complex field type contains a list of one or more context-specific <code>ErrorParameter</code> objects, with each item in the list entry being a parameter (or input field name) that caused an error condition. Each <code>ErrorParameter</code> object consists of two fields, a <code>name</code> and a <code>value</code>.',
    )
    subdomain: Optional[str] = Field(
        None,
        description="Name of the domain's subsystem or subdivision. For example, checkout is a subdomain in the buying domain.",
    )


class ExtendedProducerResponsibilityPolicyResponse(BaseModel):
    extendedProducerResponsibilities: Optional[
        List[ExtendedProducerResponsibilityPolicy]
    ] = Field(
        None,
        description='An array of response fields detailing the Extended Producer Responsibility policies supported for the specified marketplace.',
    )
    warnings: Optional[List[Error]] = Field(
        None, description='A collection of warnings generated for the request.'
    )


class HazardousMaterialDetailsResponse(BaseModel):
    pictograms: Optional[List[Pictogram]] = Field(
        None,
        description='This array contains of available hazardous materials hazard pictograms for the specified marketplace.',
    )
    signalWords: Optional[List[SignalWord]] = Field(
        None,
        description='This array contains available hazardous materials signal words for the specified marketplace.',
    )
    statements: Optional[List[HazardStatement]] = Field(
        None,
        description='This array contains available hazardous materials hazard statements for the specified marketplace.',
    )


class ItemConditionPolicyResponse(BaseModel):
    itemConditionPolicies: Optional[List[ItemConditionPolicy]] = Field(
        None,
        description="A list of category IDs and the policies for how to indicate an item's condition in each of the listed categories.",
    )
    warnings: Optional[List[Error]] = Field(
        None,
        description='A list of the warnings that were generated as a result of the request. This field is not returned if no warnings were generated by the request.',
    )


class ListingStructurePolicyResponse(BaseModel):
    listingStructurePolicies: Optional[List[ListingStructurePolicy]] = Field(
        None,
        description='Returns a list of category IDs plus a flag indicating whether or not each listed category supports item variations.',
    )
    warnings: Optional[List[Error]] = Field(
        None,
        description='A list of the warnings that were generated as a result of the request. This field is not returned if no warnings were generated by the request.',
    )


class NegotiatedPricePolicyResponse(BaseModel):
    negotiatedPricePolicies: Optional[List[NegotiatedPricePolicy]] = Field(
        None,
        description='A list of category IDs and the policies related to negotiated-price items for each of the listed categories.',
    )
    warnings: Optional[List[Error]] = Field(
        None,
        description='A list of the warnings that were generated as a result of the request. This field is not returned if no warnings were generated by the request.',
    )


class ReturnPolicyDetails(BaseModel):
    policyDescriptionEnabled: Optional[bool] = Field(
        None,
        description="If set to <code>true</code>, this flag indicates you can supply a detailed return policy description within your return policy (for example, by populating the <b>returnInstructions</b> field in the Account API's <b>createReturnPolicy</b>). User-supplied return policy details are allowed only in the DE, ES, FR, and IT marketplaces.",
    )
    refundMethods: Optional[List[str]] = Field(
        None,
        description='A list of refund methods allowed for the associated category.',
    )
    returnMethods: Optional[List[str]] = Field(
        None,
        description='A list of return methods allowed for the associated category.',
    )
    returnPeriods: Optional[List[TimeDuration]] = Field(
        None,
        description='A list of return periods allowed for the associated category.  <br><br>Note that different APIs require you to enter the return period in different ways. For example, the Account API uses the complex <b>TimeDuration</b> type, which takes two values (a <b>unit</b> and a <b>value</b>), whereas the Trading API takes a single value (such as <code>Days_30</code>).',
    )
    returnShippingCostPayers: Optional[List[str]] = Field(
        None,
        description='A list of allowed values for who pays for the return shipping cost.  <br><br>Note that for SNAD returns, the seller is always responsible for the return shipping cost.',
    )
    returnsAcceptanceEnabled: Optional[bool] = Field(
        None,
        description='If set to <code>true</code>, this flag indicates the seller can configure how they handle domestic returns.',
    )


class AutomotivePartsCompatibilityPolicyResponse(BaseModel):
    automotivePartsCompatibilityPolicies: Optional[
        List[AutomotivePartsCompatibilityPolicy]
    ] = Field(
        None,
        description='A list of category IDs and the automotive-parts-compatibility policies for each of the listed categories.',
    )
    warnings: Optional[List[Error]] = Field(
        None,
        description='A list of the warnings that were generated as a result of the request. This field is not returned if no warnings were generated by the request.',
    )


class ReturnPolicy(BaseModel):
    categoryId: Optional[str] = Field(
        None, description='The category ID to which the return policies apply.'
    )
    categoryTreeId: Optional[str] = Field(
        None,
        description='A value that indicates the root node of the category tree used for the response set. Each marketplace is based on a category tree whose root node is indicated by this unique category ID value. All category policy information returned by this call pertains to the categories included below this root node of the tree.    <br><br>A <i>category tree</i> is a hierarchical framework of eBay categories that begins at the root node of the tree and extends to include all the child nodes in the tree. Each child node in the tree is an eBay category that is represented by a unique <b>categoryId</b> value. Within a category tree, the root node has no parent node and <i>leaf nodes</i> are nodes that have no child nodes.',
    )
    domestic: Optional[ReturnPolicyDetails] = Field(
        None,
        description='This complex type defines the category policies related to domestic item returns.',
    )
    international: Optional[ReturnPolicyDetails] = Field(
        None,
        description='This complex type defines the category policies related to international item returns.',
    )
    required: Optional[bool] = Field(
        None,
        description='If set to <code>true</code>, this flag indicates that you must specify a return policy for items listed in the associated category.  <br><br>Note that not accepting returns (setting <b>returnsAcceptedEnabled</b> to <code>false</code>) is a valid return policy.',
    )


class ReturnPolicyResponse(BaseModel):
    returnPolicies: Optional[List[ReturnPolicy]] = Field(
        None,
        description='A list of elements, where each contains a category ID and a flag that indicates whether or not listings in that category require a return policy.',
    )
    warnings: Optional[List[Error]] = Field(
        None,
        description='A list of the warnings that were generated as a result of the request. This field is not returned if no warnings were generated by the request.',
    )
